# Generated by Django 3.1.4 on 2021-01-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_stocks_boughttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
