# Generated by Django 3.1.5 on 2021-01-23 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_stocks_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocks',
            old_name='amount',
            new_name='quantity_owned',
        ),
    ]
